# Generated by Django 4.2 on 2023-09-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("Student_ID", models.IntegerField(primary_key=True, serialize=False)),
                ("Test_1", models.DecimalField(decimal_places=2, max_digits=5)),
                ("Test_2", models.DecimalField(decimal_places=2, max_digits=5)),
                ("Test_3", models.DecimalField(decimal_places=2, max_digits=5)),
                ("Test_4", models.DecimalField(decimal_places=2, max_digits=5)),
                ("Test_5", models.DecimalField(decimal_places=2, max_digits=5)),
                ("Test_6", models.DecimalField(decimal_places=2, max_digits=5)),
                ("Test_7", models.DecimalField(decimal_places=2, max_digits=5)),
                ("Test_8", models.DecimalField(decimal_places=2, max_digits=5)),
                ("Test_9", models.DecimalField(decimal_places=2, max_digits=5)),
                ("Test_10", models.DecimalField(decimal_places=2, max_digits=5)),
                ("Test_11", models.DecimalField(decimal_places=2, max_digits=5)),
                ("Test_12", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
